#!/usr/bin/env node
'use strict';

var filename = require("../").getPathTo("elm-package");
var spawn = require("child_process").spawn;
var input = process.argv.slice(2);

spawn(filename, input, {stdio: 'inherit'})
    .on('exit', process.exit);
